### ISSUE TITLE
composer with curl depricated

### ISSUE THREAD

**Issue by pboethig** [schmengler/magento-boilerplate#13]
Since a the composer guys disables curl calls to get composer. Vagrant provisioning fails on that point

Here is the fix
https://github.com/puphpet/puppet-puphpet/commit/659fc6d6548dd8158fdac7bb834111c769854a98

3  manifests/php/composer.pp
 @@ -31,11 +31,10 @@
    class { '::composer':
      target_dir      => '/usr/local/bin',
      composer_file   => 'composer',
 -    download_method => 'curl',
 +    download_method => 'wget',
      logoutput       => false,
      tmp_path        => '/tmp',
      php_package     => $php_package,
 -    curl_package    => 'curl',
      suhosin_enabled => false,

**Comment by schmengler** [comment]
fixed by #16
