### ISSUE TITLE
New SSH key generated at each boot

### ISSUE THREAD

**Issue by riker09** [schmengler/magento-boilerplate#5]
Everytime I startup the machine with `./up` I see messages like these:

```sh
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
```

I'm wondering if this is intended behavior and I openly admit, that I'm far from being an expert on this. It just seems unnecessary and costs a little more time on each boot process. Is it possible to avoid this?

**Comment by riker09** [comment]
I just noticed, this is also executed on each halt/shutdown.

**Comment by schmengler** [comment]
This is a Vagrant feature. You can disable it with `insert_key: false` in the `ssh` section of `config.yaml` (or set a `private_key_path` explicitly to not use the generated insecure key at all)

Read more: https://docs.vagrantup.com/v2/vagrantfile/ssh_settings.html
